version: 0.2

env:
  variables:
    FRAMEWORK_VERSION: '1.1.0'
    CPU_PY_VERSION: '2'
    CPU_INSTANCE_TYPE: 'ml.c4.xlarge'
    GPU_PY_VERSION: '3'
    GPU_INSTANCE_TYPE: 'ml.p2.xlarge'
    LOCAL_BASE_REPO: 'pytorch-base'
    ECR_REPO: 'sagemaker-test'
    GITHUB_REPO: 'sagemaker-pytorch-container'
    SETUP_FILE: 'setup_cmds.sh'
    SETUP_CMDS: '#!/bin/bash\npip install --upgrade pip\npip install -U -e .\npip install -U -e .[test]'


phases:
  pre_build:
    commands:
      - start-dockerd
      - ACCOUNT=$(aws sts get-caller-identity --query 'Account' --output text)
      - PREPROD_IMAGE="$ACCOUNT.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO"
      - PR_NUM=$(echo $CODEBUILD_SOURCE_VERSION | grep -o '[0-9]\+')
      - echo 'Pull request number:' $PR_NUM '. No value means this build is not from pull request.'

  build:
    commands:
      # install
      - pip3 install -U -e .
      - pip3 install -U -e .[test]

      # run unit tests
      - pytest test/unit

      # build cpu base image
      - base_dir="docker/$FRAMEWORK_VERSION/base"
      - cpu_py2_base_tag="$FRAMEWORK_VERSION-cpu-py2"
      - cpu_py3_base_tag="$FRAMEWORK_VERSION-cpu-py3"
      - cpu_dockerfile="Dockerfile.cpu"
      - cd $base_dir
      - docker build -t $LOCAL_BASE_REPO:$cpu_py2_base_tag -f $cpu_dockerfile --build-arg py_version=2 .
      - docker build -t $LOCAL_BASE_REPO:$cpu_py3_base_tag -f $cpu_dockerfile --build-arg py_version=3 .
      - cd ../../../

      # build gpu base image
      - gpu_py2_base_tag="$FRAMEWORK_VERSION-gpu-py2"
      - gpu_py3_base_tag="$FRAMEWORK_VERSION-gpu-py3"
      - gpu_dockerfile="Dockerfile.gpu"
      - cd $base_dir
      - docker build -t $LOCAL_BASE_REPO:$gpu_py2_base_tag -f $gpu_dockerfile --build-arg py_version=2 .
      - docker build -t $LOCAL_BASE_REPO:$gpu_py3_base_tag -f $gpu_dockerfile --build-arg py_version=3 .
      - cd ../../../

      # create wheel
      - python3 setup.py bdist_wheel

      # build cpu image
      - build_dir="docker/$FRAMEWORK_VERSION/final"
      - build_id="$(echo $CODEBUILD_BUILD_ID | sed -e 's/:/-/g')"
      - CPU_PY2_TAG="$FRAMEWORK_VERSION-cpu-py2-$build_id"
      - CPU_PY3_TAG="$FRAMEWORK_VERSION-cpu-py3-$build_id"
      - docker build -f "$build_dir/$cpu_dockerfile" --build-arg py_version=2 -t $PREPROD_IMAGE:$CPU_PY2_TAG .
      - docker build -f "$build_dir/$cpu_dockerfile" --build-arg py_version=3 -t $PREPROD_IMAGE:$CPU_PY3_TAG .

      # build gpu image
      - GPU_PY2_TAG="$FRAMEWORK_VERSION-gpu-py2-$build_id"
      - docker build -f "$build_dir/$gpu_dockerfile" --build-arg py_version=2 -t $PREPROD_IMAGE:$GPU_PY2_TAG .
      - docker build -f "$build_dir/$gpu_dockerfile" --build-arg py_version=3 -t $PREPROD_IMAGE:$GPU_PY3_TAG .

      # push images to ecr
      - $(aws ecr get-login --registry-ids $ACCOUNT --no-include-email --region $AWS_DEFAULT_REGION)
      - docker push $PREPROD_IMAGE:$CPU_PY2_TAG
      - docker push $PREPROD_IMAGE:$CPU_PY3_TAG
      - docker push $PREPROD_IMAGE:$GPU_PY2_TAG
      - docker push $PREPROD_IMAGE:$GPU_PY3_TAG

      # launch remote gpu instance
      - prefix='ml.'
      - instance_type=${GPU_INSTANCE_TYPE#"$prefix"}
      - create-key-pair
      - launch-ec2-instance --instance-type $instance_type --ami-name dlami-ubuntu

      # run cpu integration tests
      - |
        if has-matching-changes "test/" "tests/" "src/*.py" "docker/*" "buildspec.yml"; then
          pytest test/integration/local --region $AWS_DEFAULT_REGION --docker-base-name $PREPROD_IMAGE --tag $CPU_PY2_TAG --framework-version $FRAMEWORK_VERSION --py-version 2 --processor cpu
        else
          echo "skipping cpu integration tests"
        fi

      # run gpu integration tests
      - |
        if has-matching-changes "test/" "tests/" "src/*.py" "docker/*" "buildspec.yml"; then
          printf "$SETUP_CMDS" > $SETUP_FILE
          py2_cmd="pytest test/integration/local --region $AWS_DEFAULT_REGION --docker-base-name $PREPROD_IMAGE --tag $GPU_PY2_TAG --framework-version $FRAMEWORK_VERSION --py-version 2 --processor gpu"
          py3_cmd="pytest test/integration/local --region $AWS_DEFAULT_REGION --docker-base-name $PREPROD_IMAGE --tag $GPU_PY3_TAG --framework-version $FRAMEWORK_VERSION --py-version 3 --processor gpu"
          remote-test --github-repo $GITHUB_REPO --test-cmd "$py2_cmd" --setup-file $SETUP_FILE --pr-number "$PR_NUM"
          remote-test --github-repo $GITHUB_REPO --test-cmd "$py3_cmd" --setup-file $SETUP_FILE --pr-number "$PR_NUM"
        else
          echo "skipping gpu integration tests"
        fi

      # run cpu sagemaker tests
      - |
        if has-matching-changes "test/" "tests/" "src/*.py" "docker/*" "buildspec.yml"; then
          pytest test/integration/sagemaker --region $AWS_DEFAULT_REGION --docker-base-name $ECR_REPO --aws-id $ACCOUNT --tag $CPU_PY2_TAG --instance-type $CPU_INSTANCE_TYPE
          pytest test/integration/sagemaker --region $AWS_DEFAULT_REGION --docker-base-name $ECT_REPO --aws-id $ACCOUNT --tag $CPU_PY3_TAG --instance-type $CPU_INSTANCE_TYPE
        else
          echo "skipping cpu sagemaker tests"
        fi

      # run gpu sagemaker tests
      - |
        if has-matching-changes "test/" "tests/" "src/*.py" "docker/*" "buildspec.yml"; then
          pytest test/integration/sagemaker --region $AWS_DEFAULT_REGION --docker-base-name $ECR_REPO --aws-id $ACCOUNT --tag $GPU_PY2_TAG --instance-type $GPU_INSTANCE_TYPE
          pytest test/integration/sagemaker --region $AWS_DEFAULT_REGION --docker-base-name $ECR_REPO --aws-id $ACCOUNT --tag $GPU_PY3_TAG --instance-type $GPU_INSTANCE_TYPE
        else
          echo "skipping gpu sagemaker tests"
        fi

    finally:
      # shut down remote gpu instance
      - cleanup-gpu-instances
      - cleanup-key-pairs

      # remove ecr image
      - aws ecr batch-delete-image --repository-name $ECR_REPO --region $AWS_DEFAULT_REGION --image-ids imageTag=$CPU_PY2_TAG
      - aws ect batch-delete-image --repository-name $ECT_REPO --region $AWS_DEFAULT_REGION --image-ids imageTag=$CPU_PY3_TAG
      - aws ecr batch-delete-image --repository-name $ECR_REPO --region $AWS_DEFAULT_REGION --image-ids imageTag=$GPU_PY2_TAG
      - aws ecr batch-delete-image --repository-name $ECT_REPO --region $AWS_DEFAULT_REGION --image-ids imageTag=$GPU_PY3_TAG
