FROM pytorch-base:0.3.1-cpu-py3

COPY dist/sagemaker_pytorch_container-1.0-py2.py3-none-any.whl /sagemaker_pytorch_container-1.0-py2.py3-none-any.whl
RUN pip install /sagemaker_pytorch_container-1.0-py2.py3-none-any.whl && rm /sagemaker_pytorch_container-1.0-py2.py3-none-any.whl

# Starts framework
ENTRYPOINT ["python", "-m", "pytorch_container.start"]
