blank_issues_enabled: false
contact_links:
  - name: Ask a question related to SageMaker
    url: https://stackoverflow.com/questions/tagged/amazon-sagemaker
    about: Use Stack Overflow to ask and answer questions about SageMaker
  - name: Ask a question related to PyTorch
    url: https://discuss.pytorch.org
    about: Use the PyTorch Forums to ask and answer questions about PyTorch
